name: CI build test of s1 s2 s3 and db services

on:
  push:
    branches: [ main ]
    paths:
      - cluster/../*
      - cluster/*
      - db/*
      - ci/*
      - s1/*
      - s3/*
      - s2/*
      - s2/v1/*
      - ci/v1/*
      - .github/workflows/ci-system-v1.yaml

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_COMPOSE_VER: v2.2.2
      ARCH_CLASS: x86_64
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install docker-compose v2.2.2
        # As of Dec 2021, the only way to guarantee that we have docker-compose v2.2.2 is to install it ourselves
        # (See answer to https://github.com/actions/virtual-environments/issues/4657)
        # The GitHub docs claim that docker-compose 2.2.2 is available in the Unbuntu 20.04 runner but do not provide
        # any documentation for how to invoke it.
        run: |
          curl -L "https://github.com/docker/compose/releases/download/${{ env.DOCKER_COMPOSE_VER }}/docker-compose-linux-${{ env.ARCH_CLASS }}" \
             -o tools/docker-compose-v2
          chmod +x tools/docker-compose-v2

      - name: Instantiate template files
        # For CI, only need ZZ-REG-ID to instantiate s2/standalone/unique_code-tpl.py
        run: |
          sed -e "s/ZZ-REG-ID=.*/ZZ-REG-ID=${{ github.repository_owner }}/" cluster/tpl-vars-blank.txt > cluster/tpl-vars.txt
          make -f k8s-tpl.mak templates

      - name: Build Test S2 Service
        run: |
          cd s2/standalone/
          ./builda3.sh
          cd ../..
      
      - name: Build Test S1 Service
        run: |
          cd s2/test/
          make build-music_test
          cd ../..
      
      - name: Build Test S3 Service
        run: |
          cd s3
          docker image build --platform linux/amd64 -t cmpt756s3 .
          cd ../

      - name: Build Test DB Service
        run: |
          cd db
          docker image build --platform linux/amd64 -t cmpt756db .
          cd ../

      - name: Run CI test
        run: |
          cd ci
          COMPOSE_PATH=../tools/docker-compose-v2 ./runci.sh v1
